// <auto-generated />
namespace XANDER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pleasegod46withextradip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pleasegod46withextradip));
        
        string IMigrationMetadata.Id
        {
            get { return "201805292036352_please god #46 with extra dip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
