// <auto-generated />
namespace XANDER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1041 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1041));
        
        string IMigrationMetadata.Id
        {
            get { return "201805181541284_1041"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
